language: android
node_js:
  - '0.10'
cache:
  directories:
    - node_modules
    - app/bower_components
android:
  components:
    - android-22
addons:
  apt:
    packages:
      - libgnome-keyring-dev
before_script:
  - npm install --global bower grunt-cli
  - npm install
  - bower install
script:
  - npm test
after_success:
  - ./scripts/upload_to_transifex.sh
notifications:
  flowdock: 232485f7661e644ae5878944c2597042
before_deploy:
  - ./scripts/build-travis.sh
deploy:
  # snapshots
  provider: s3
  access_key_id: AKIAJJE2IH3G7K5ZRZWQ
  secret_access_key:
    secure: who37ATPHOwXVusY8i5kiCkN5qPv2MrF1MVwz4mmoweCrCTAmCOvY76n4KB3DpLl3vQPAathFvOTAcLCAczo7+sTmwZ5v0D4WVIRNYnnSEdriEoc9UiTjhJqwrvWMDbNwKZs/DELlX8icXCJleLOQ6BxF4Nva455vbAIurW/u5A2TmSpMfipz7wm9DWylc4lfHtkesqkj49c0VxDOKGMk5Fp8of1QAaLrWydS90t/XmgMKUVoQUPAw7WeHB9j2Uc13IPxoSUdahw4SoeS1978neGZAy1aSih1oLYKKrSPqe0iHp6jX3q5vkeltK4OXt0tx/O9WVKjRoYbILIg+9AIjYSe1l+onrLeDmQ8df8EWKOlNcqv964wlBvJdl+wuEx7pxnEygD0DnFyU4dMCLEuFzD5tY5PtYlNoCabGBVhg+0q82bHGYzNAOM6UjaAiB0diUNn4j+X9oQuXzexnga4HDLnKVUiSmOnQYxl/phTKyOTZr03mwYbtk8s5NCl+3aMJQP2vmNJZvBJ0XrNkT663IyWoB3m8O5iHR/k5haBqr8rpPM7ucQpShoqED5oGlw6l245MNg+nYmcdwIULxTf7IE6DNrNQw5kuPjs9C3iVNq8hsyFMYvEUNYselZE6YLH290FEiOp522D1BPyM5C4FSQoBRKUGKb7V2Bvdmb6PM=
  bucket: eha-move
  local-dir: build
  skip_cleanup: true
  upload-dir: snapshots
  region: eu-west-1
  on:
    branch: develop
    repo: eHealthAfrica/move
  # release versions
  provider: s3
  access_key_id: AKIAJJE2IH3G7K5ZRZWQ
  secret_access_key:
    secure: who37ATPHOwXVusY8i5kiCkN5qPv2MrF1MVwz4mmoweCrCTAmCOvY76n4KB3DpLl3vQPAathFvOTAcLCAczo7+sTmwZ5v0D4WVIRNYnnSEdriEoc9UiTjhJqwrvWMDbNwKZs/DELlX8icXCJleLOQ6BxF4Nva455vbAIurW/u5A2TmSpMfipz7wm9DWylc4lfHtkesqkj49c0VxDOKGMk5Fp8of1QAaLrWydS90t/XmgMKUVoQUPAw7WeHB9j2Uc13IPxoSUdahw4SoeS1978neGZAy1aSih1oLYKKrSPqe0iHp6jX3q5vkeltK4OXt0tx/O9WVKjRoYbILIg+9AIjYSe1l+onrLeDmQ8df8EWKOlNcqv964wlBvJdl+wuEx7pxnEygD0DnFyU4dMCLEuFzD5tY5PtYlNoCabGBVhg+0q82bHGYzNAOM6UjaAiB0diUNn4j+X9oQuXzexnga4HDLnKVUiSmOnQYxl/phTKyOTZr03mwYbtk8s5NCl+3aMJQP2vmNJZvBJ0XrNkT663IyWoB3m8O5iHR/k5haBqr8rpPM7ucQpShoqED5oGlw6l245MNg+nYmcdwIULxTf7IE6DNrNQw5kuPjs9C3iVNq8hsyFMYvEUNYselZE6YLH290FEiOp522D1BPyM5C4FSQoBRKUGKb7V2Bvdmb6PM=
  bucket: eha-move
  local-dir: build
  upload-dir: releases
  skip_cleanup: true
  region: eu-west-1
  on:
    tags: true
    all_branches: true
    repo: eHealthAfrica/move
env:
  global:
    # grunt-angular-gettext-transifex
    - secure: "bohBhvuwhB5GWNHHfH2wcOdATaPlRdRd9OmHEIU3D7qOZwDGNzs4do+WhAMKHOfVQZ2a4pJ/frVutNE2eIkikcsNWGpFxgkyKbJF5PEo0FAhHPZ0qXcOgB5Q5UJ4Ug8/KhNEAsHOGIG8Fxnsfsopet3tLC2vc5FghCCxil649bf8qIOMKxV20NwHhNHybuzrPf7cbopwu0H0wrb1KGpnh1evpr9+fCx0vLZ0gNAGvKJaAFYJnTl5+n9z7dmfY4AfeVLnvpSZXeo8WYjdJ44t19AT/p3mMuEHsRPW2frjMu8yYjem2S/xKmQTvIS4SLTae6uSsZissbDCRffXujrP39YBARaRrfuzI8u4Ll1idugipCVcAH873tnBCau9UQtyQ76l4QPpv176UfJhs2CtZJYyQ0L23S4s7MVc5rHnW5T8HHM1jtCZj8It5t9ZJFiuErTx2RFbTQXB3HmF7oDXg7oNHqDuQIaq2yUY8qxoTsGVu4bW6wuR+srAaKBEKShzMDNeLWkrm+BZKRUdbGq1aGILLB46L33M9eoqP3owv6MgGiu3j6CLbcInVJjdNUSGc6J34t4bn0SOjD97HUNSWck15qNcuYoYpRjgeoQrj/5ICYM9SyQ5Q14EkdU5lLBAwpCXcQhfGh59Jh9WNMIrtnftpWvDhz95bV/AfcTWjpQ="
    - secure: "FMK7cOwPQksQ6J76bKGR4AM416wgsg4nABToqT3eA1o8RVAX1NJMGfcSycmG1S1DmvxMgSmQAysz+tE1BUEFSkvNrdmXa+NkVJR1cix/HW5b3Q17sDtM+Bl6Jx+CI/cLeUJ7ahBAeEL7UgUj5kiq3qkK9ksAaH2/6aTWr0WCfto8tf08vsUelftwmN9feth6PDPrGn6CRqHt/nevLIY7/DDle5fcaQa1GweIS5ip+zj5x9zEaIZDk8BrovToYz7k2CUmAYkY0UmQklAjEUHqhzRFvycLFfVld6dZLJVzjF9fnuatZs5y1CHeG7CR9DVJ2GyjaVhYg7nroRHPD9dQtL9cCEQDMKUno+fHGrfoRo3QZ0aFTi2a88/IWIEGahDlOd30SrO2yuCVhJZ67FLK2UeXoGHMuC38lvhlOvIXtnwMYKGhW2qvJQucnekx/2iWS+cmMCLiFCjdw5VORxoo5rVEzL6qWAEImXi3MkzGWr2tQZm5o8LJazPvjqwqxb9T0aRgNR7Ho2u4xrLvsP5wxXV3+uZA/o2o5QC67oBbgTVh31iQDxehD7ujbOJyyyENKUtXousv4m+GIEEno0ye1CiMxrS320QnFBHeVLNPdz4+dO2exR9pFcDvgPsZKnVJlVj64z4LDgmBBWKU9UXJBg97DXgQinkLt2dejNbUYCo="
